const mongoose=require('mongoose');

const Schema=mongoose.Schema;

const userSchema=new Schema({
    userName:{
        type:String,
        required:true
    },
    email:{
        type:String,
        unique:true,
        required:true
    },
    password:{
        type:String,
        default:null
    },
    dateOfBirth:{
        type:String,
        default:null
    },
    phoneNumber:{
        type:String,
        defaults:null
    },
    isMailVerfied:{
        type:Boolean,
        default:false
    },
    isPhoneVerfied:{
        type:Boolean,
        default:false
    },
    phoneNumber:{
        type:String,
        unique:true,
    },
    addhaarId:{
        type:String,
        default:null
    },
    panCard:{
        type:String,
        default:null
    },
    accountNumber:{
        type:String,
        default:null
    },
    gstNumber:{
        type:String,
        default:null
    },
    isGstVerifed:{
        type:Boolean,
        default:false
    },
    password:{
        type:String,
        // required:true
    },
    isMailVerfied:{
        type:Boolean
    },
    isPhoneNumberVerified:{
        type:Boolean
    },
    isPanVerified:{
        type:Boolean,
        default:false
    },
    isBankAccountVerified:{
        type:Boolean,
        default:false
    },
    isAccountVerified:{
        type:Boolean,
        default:false
    }
})

module.exports=mongoose.model("userSchema",userSchema);